export type SouthAfricanLocation = {
  suburb: string;
  city: string;
  province: string;
};

const RAW_LOCATIONS: SouthAfricanLocation[] = [
  { suburb: "Sandton", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Bryanston", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Fourways", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Rosebank", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Melrose", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Randburg", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Midrand", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Centurion", city: "Centurion", province: "Gauteng" },
  { suburb: "Pretoria East", city: "Pretoria", province: "Gauteng" },
  { suburb: "Bedfordview", city: "Ekurhuleni", province: "Gauteng" },
  { suburb: "Edenvale", city: "Ekurhuleni", province: "Gauteng" },
  { suburb: "Kempton Park", city: "Ekurhuleni", province: "Gauteng" },
  { suburb: "Parkhurst", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Parkview", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Parktown", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Greenside", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Emmarentia", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Northcliff", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Fairland", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Melville", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Norwood", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Oaklands", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Houghton Estate", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Killarney", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Illovo", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Hyde Park", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Dunkeld", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Craighall Park", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Morningside", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Rivonia", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Sunninghill", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Lonehill", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Paulshof", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Douglasdale", city: "Johannesburg", province: "Gauteng" },
  { suburb: "North Riding", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Roodepoort", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Florida", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Weltevreden Park", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Krugersdorp", city: "Mogale City", province: "Gauteng" },
  { suburb: "Soweto", city: "Johannesburg", province: "Gauteng" },
  { suburb: "Alberton", city: "Ekurhuleni", province: "Gauteng" },
  { suburb: "Germiston", city: "Ekurhuleni", province: "Gauteng" },
  { suburb: "Boksburg", city: "Ekurhuleni", province: "Gauteng" },
  { suburb: "Benoni", city: "Ekurhuleni", province: "Gauteng" },
  { suburb: "Brakpan", city: "Ekurhuleni", province: "Gauteng" },
  { suburb: "Springs", city: "Ekurhuleni", province: "Gauteng" },
  { suburb: "Vanderbijlpark", city: "Emfuleni", province: "Gauteng" },
  { suburb: "Vereeniging", city: "Emfuleni", province: "Gauteng" },
  { suburb: "Hatfield", city: "Pretoria", province: "Gauteng" },
  { suburb: "Brooklyn", city: "Pretoria", province: "Gauteng" },
  { suburb: "Waterkloof", city: "Pretoria", province: "Gauteng" },
  { suburb: "Menlyn", city: "Pretoria", province: "Gauteng" },
  { suburb: "Garsfontein", city: "Pretoria", province: "Gauteng" },
  { suburb: "Moreleta Park", city: "Pretoria", province: "Gauteng" },
  { suburb: "Faerie Glen", city: "Pretoria", province: "Gauteng" },
  { suburb: "Lynnwood", city: "Pretoria", province: "Gauteng" },
  { suburb: "Silver Lakes", city: "Pretoria", province: "Gauteng" },
  { suburb: "Montana", city: "Pretoria", province: "Gauteng" },
  { suburb: "Rooihuiskraal", city: "Centurion", province: "Gauteng" },
  { suburb: "Die Hoewes", city: "Centurion", province: "Gauteng" },
  { suburb: "Claremont", city: "Cape Town", province: "Western Cape" },
  { suburb: "Rondebosch", city: "Cape Town", province: "Western Cape" },
  { suburb: "Newlands", city: "Cape Town", province: "Western Cape" },
  { suburb: "Wynberg", city: "Cape Town", province: "Western Cape" },
  { suburb: "Constantia", city: "Cape Town", province: "Western Cape" },
  { suburb: "Bishopscourt", city: "Cape Town", province: "Western Cape" },
  { suburb: "Kenilworth", city: "Cape Town", province: "Western Cape" },
  { suburb: "Observatory", city: "Cape Town", province: "Western Cape" },
  { suburb: "Woodstock", city: "Cape Town", province: "Western Cape" },
  { suburb: "Gardens", city: "Cape Town", province: "Western Cape" },
  { suburb: "Sea Point", city: "Cape Town", province: "Western Cape" },
  { suburb: "Green Point", city: "Cape Town", province: "Western Cape" },
  { suburb: "Camps Bay", city: "Cape Town", province: "Western Cape" },
  { suburb: "Bantry Bay", city: "Cape Town", province: "Western Cape" },
  { suburb: "Hout Bay", city: "Cape Town", province: "Western Cape" },
  { suburb: "Noordhoek", city: "Cape Town", province: "Western Cape" },
  { suburb: "Muizenberg", city: "Cape Town", province: "Western Cape" },
  { suburb: "Fish Hoek", city: "Cape Town", province: "Western Cape" },
  { suburb: "Simonstown", city: "Cape Town", province: "Western Cape" },
  { suburb: "Durbanville", city: "Cape Town", province: "Western Cape" },
  { suburb: "Bellville", city: "Cape Town", province: "Western Cape" },
  { suburb: "Brackenfell", city: "Cape Town", province: "Western Cape" },
  { suburb: "Kraaifontein", city: "Cape Town", province: "Western Cape" },
  { suburb: "Milnerton", city: "Cape Town", province: "Western Cape" },
  { suburb: "Table View", city: "Cape Town", province: "Western Cape" },
  { suburb: "Bloubergstrand", city: "Cape Town", province: "Western Cape" },
  { suburb: "Century City", city: "Cape Town", province: "Western Cape" },
  { suburb: "Somerset West", city: "Cape Town", province: "Western Cape" },
  { suburb: "Strand", city: "Cape Town", province: "Western Cape" },
  { suburb: "Stellenbosch", city: "Stellenbosch", province: "Western Cape" },
  { suburb: "Paarl", city: "Drakenstein", province: "Western Cape" },
  { suburb: "Franschhoek", city: "Stellenbosch", province: "Western Cape" },
  { suburb: "George", city: "George", province: "Western Cape" },
  { suburb: "Mossel Bay", city: "Mossel Bay", province: "Western Cape" },
  { suburb: "Knysna", city: "Knysna", province: "Western Cape" },
  { suburb: "Plettenberg Bay", city: "Bitou", province: "Western Cape" },
  { suburb: "Umhlanga", city: "Durban", province: "KwaZulu-Natal" },
  { suburb: "La Lucia", city: "Durban", province: "KwaZulu-Natal" },
  { suburb: "Durban North", city: "Durban", province: "KwaZulu-Natal" },
  { suburb: "Morningside", city: "Durban", province: "KwaZulu-Natal" },
  { suburb: "Berea", city: "Durban", province: "KwaZulu-Natal" },
  { suburb: "Musgrave", city: "Durban", province: "KwaZulu-Natal" },
  { suburb: "Glenwood", city: "Durban", province: "KwaZulu-Natal" },
  { suburb: "Westville", city: "Durban", province: "KwaZulu-Natal" },
  { suburb: "Pinetown", city: "Durban", province: "KwaZulu-Natal" },
  { suburb: "Kloof", city: "Durban", province: "KwaZulu-Natal" },
  { suburb: "Hillcrest", city: "Durban", province: "KwaZulu-Natal" },
  { suburb: "Ballito", city: "KwaDukuza", province: "KwaZulu-Natal" },
  { suburb: "Salt Rock", city: "KwaDukuza", province: "KwaZulu-Natal" },
  { suburb: "Amanzimtoti", city: "Durban", province: "KwaZulu-Natal" },
  { suburb: "Scottburgh", city: "Umdoni", province: "KwaZulu-Natal" },
  { suburb: "Pietermaritzburg", city: "Msunduzi", province: "KwaZulu-Natal" },
  { suburb: "Hilton", city: "Msunduzi", province: "KwaZulu-Natal" },
  { suburb: "Howick", city: "uMngeni", province: "KwaZulu-Natal" },
  { suburb: "Richards Bay", city: "uMhlathuze", province: "KwaZulu-Natal" },
  { suburb: "Margate", city: "Ray Nkonyeni", province: "KwaZulu-Natal" },
  { suburb: "Summerstrand", city: "Gqeberha", province: "Eastern Cape" },
  { suburb: "Humewood", city: "Gqeberha", province: "Eastern Cape" },
  { suburb: "Walmer", city: "Gqeberha", province: "Eastern Cape" },
  { suburb: "Mill Park", city: "Gqeberha", province: "Eastern Cape" },
  { suburb: "Newton Park", city: "Gqeberha", province: "Eastern Cape" },
  { suburb: "Lorraine", city: "Gqeberha", province: "Eastern Cape" },
  { suburb: "Jeffreys Bay", city: "Kouga", province: "Eastern Cape" },
  { suburb: "St Francis Bay", city: "Kouga", province: "Eastern Cape" },
  { suburb: "East London", city: "Buffalo City", province: "Eastern Cape" },
  { suburb: "Beacon Bay", city: "Buffalo City", province: "Eastern Cape" },
  { suburb: "Nahoon", city: "Buffalo City", province: "Eastern Cape" },
  { suburb: "Mthatha", city: "King Sabata Dalindyebo", province: "Eastern Cape" },
  { suburb: "Bloemfontein", city: "Mangaung", province: "Free State" },
  { suburb: "Langenhoven Park", city: "Mangaung", province: "Free State" },
  { suburb: "Dan Pienaar", city: "Mangaung", province: "Free State" },
  { suburb: "Universitas", city: "Mangaung", province: "Free State" },
  { suburb: "Fichardt Park", city: "Mangaung", province: "Free State" },
  { suburb: "Welkom", city: "Matjhabeng", province: "Free State" },
  { suburb: "Bethlehem", city: "Dihlabeng", province: "Free State" },
  { suburb: "Kimberley", city: "Sol Plaatje", province: "Northern Cape" },
  { suburb: "Kuruman", city: "Ga-Segonyana", province: "Northern Cape" },
  { suburb: "Upington", city: "Dawid Kruiper", province: "Northern Cape" },
  { suburb: "Polokwane", city: "Polokwane", province: "Limpopo" },
  { suburb: "Bendor", city: "Polokwane", province: "Limpopo" },
  { suburb: "Fauna Park", city: "Polokwane", province: "Limpopo" },
  { suburb: "Tzaneen", city: "Greater Tzaneen", province: "Limpopo" },
  { suburb: "Mokopane", city: "Mogalakwena", province: "Limpopo" },
  { suburb: "Thohoyandou", city: "Thulamela", province: "Limpopo" },
  { suburb: "Mbombela", city: "Mbombela", province: "Mpumalanga" },
  { suburb: "Nelspruit", city: "Mbombela", province: "Mpumalanga" },
  { suburb: "White River", city: "Mbombela", province: "Mpumalanga" },
  { suburb: "Hazyview", city: "Mbombela", province: "Mpumalanga" },
  { suburb: "Secunda", city: "Govan Mbeki", province: "Mpumalanga" },
  { suburb: "Witbank", city: "eMalahleni", province: "Mpumalanga" },
  { suburb: "Middelburg", city: "Steve Tshwete", province: "Mpumalanga" },
  { suburb: "Rustenburg", city: "Rustenburg", province: "North West" },
  { suburb: "Klerksdorp", city: "Matlosana", province: "North West" },
  { suburb: "Potchefstroom", city: "JB Marks", province: "North West" },
  { suburb: "Hartbeespoort", city: "Madibeng", province: "North West" },
  { suburb: "Mahikeng", city: "Mahikeng", province: "North West" },
];

function normalize(value: string) {
  return value.trim().toLowerCase();
}

export const SOUTH_AFRICAN_LOCATIONS = Array.from(
  new Map(
    RAW_LOCATIONS.map((location) => [
      `${normalize(location.suburb)}|${normalize(location.city)}|${normalize(location.province)}`,
      location,
    ])
  ).values()
).sort((a, b) => a.suburb.localeCompare(b.suburb));

export function locationLabel(location: SouthAfricanLocation) {
  return `${location.suburb}, ${location.city}`;
}

export function searchSouthAfricanLocations(query: string, limit = 12) {
  const q = normalize(query);

  const matches = q
    ? SOUTH_AFRICAN_LOCATIONS.filter((location) =>
        [location.suburb, location.city, location.province]
          .some((part) => normalize(part).includes(q))
      )
    : SOUTH_AFRICAN_LOCATIONS;

  return matches.slice(0, limit);
}
